name: mechanalyzer-env

channels:
    - auto-mech
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - pybind11
    - cmake
    - gfortran_linux-64  # [linux]
    - numpy
    - scipy
    - pandas
    - pyyaml
    - mako
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - psi4::psi4
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental 
    - conda-forge::nglview
    - conda-forge::pypdf2
    - conda-forge::python-igraph
    - cantera::cantera
    - auto-mech::autoio-base
    - auto-mech::autochem
    - auto-mech::autoio-interfaces
    - auto-mech::autofile
    - auto-mech::x2z
    - auto-mech::mess
    - auto-mech::projrot
    - auto-mech::pac99
    - auto-mech::thermp
