# cmd: conda build .  -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge

package:
    name: mechanalyzer
    version: "0.2.5"

source:
    path: .

requirements:
    host:
        - python=3.7
    run:
        - gfortran_linux-64  # [linux]
        - python=3.7
        - cmake
        - numpy=1.15.4
        - scipy=1.5.0
        - pyyaml
        - mako
        - networkx
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - psi4::psi4
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - auto-mech::autochem
        - auto-mech::autoio-base
        - auto-mech::x2z
        - auto-mech::mess
        - auto-mech::projrot
        - auto-mech::pac99
        - auto-mech::thermp
        - auto-mech::autoio-interfaces
        - auto-mech::autofile
        # - auto-mech::mechanalyzer
