name: mechanalyzer-env

channels:
    - auto-mech
    - psi4
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - pybind11
    - cmake
    - gfortran_linux-64  # [linux]
    - numpy
    - scipy
    - pandas
    - pyyaml
    - mako
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - auto-mech::automol
    - auto-mech::autoparse
    - auto-mech::autorun
    - auto-mech::autoio
    - auto-mech::elstruct
    - auto-mech::x2z
    - psi4::psi4
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental 
