# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c conda-forge
package:
    name: mechanalyzer
    version: "0.1.0"

source:
    path: .

requirements:
    host:
        - python
    build:
        - cmake
        - gfortran_linux-64
    run:
        - cmake
        - gfortran_linux-64
        - python
        - numpy
        - scipy
        - pyyaml
        - mako
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - psi4::psi4
        - auto-mech::autoio
        - auto-mech::automol
        - auto-mech::autoparse
        - auto-mech:ratefit
        # - auto-mech::mechdriver 
        - auto-mech::x2z
