# cmd: conda build . -c auto-mech -c psi4 -c rdkit -c openbabel -c cantera -c conda-forge
package:
    name: mechanalyzer
    version: "0.1.0"

source:
    path: .

requirements:
    host:
        - python=3.7
    build:
        - cmake
        - gfortran_linux-64
    run:
        - cmake
        - gfortran_linux-64
        - python=3.7
        - numpy
        - scipy
        - pyyaml
        - mako
        - matplotlib
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
        - conda-forge::nglview
        - conda-forge::pypdf2
        - conda-forge::python-igraph
        - cantera::cantera
        - psi4::psi4
        - auto-mech::autoio
        - auto-mech::automol
        - auto-mech::autoparse
        - auto-mech::elstruct
        - auto-mech::ratefit
        - auto-mech::x2z
