name: ratefit-env

channels:
    - auto-mech
     # -conda_forge # may resolve package conflicts with autoio

dependencies:
    - python=3.7
    - pybind11
    - cmake
    - gfortran_linux-64  # [linux]
    - numpy
    - scipy
    - pandas
    - pyyaml
    - mako
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - auto-mech::autoio

